# Everforest Dark Medium Palette
# https://github.com/sainnhe/everforest

$bg_dim = rgb(232a2e)
$bg_dimAlpha = 232a2e
$bg0 = rgb(2d353b)
$bg0Alpha = 2d353b
$bg1 = rgb(343f44)
$bg1Alpha = 343f44
$bg2 = rgb(3d484d)
$bg2Alpha = 3d484d
$bg3 = rgb(475258)
$bg3Alpha = 475258
$bg4 = rgb(4f585e)
$bg4Alpha = 4f585e
$bg5 = rgb(56635f)
$bg5Alpha = 56635f
$bg_red = rgb(514045)
$bg_redAlpha = 514045
$bg_yellow = rgb(4d4c43)
$bg_yellowAlpha = 4d4c43
$bg_green = rgb(425047)
$bg_greenAlpha = 425047
$bg_blue = rgb(3a515d)
$bg_blueAlpha = 3a515d
$bg_purple = rgb(4a444e)
$bg_purpleAlpha = 4a444e
$bg_visual = rgb(543a48)
$bg_visualAlpha = 543a48
$fg = rgb(d3c6aa)
$fgAlpha = d3c6aa
$red = rgb(e67e80)
$redAlpha = e67e80
$orange = rgb(e69875)
$orangeAlpha = e69875
$yellow = rgb(dbbc7f)
$yellowAlpha = dbbc7f
$green = rgb(a7c080)
$greenAlpha = a7c080
$aqua = rgb(83c092)
$aquaAlpha = 83c092
$blue = rgb(7fbbb3)
$blueAlpha = 7fbbb3
$purple = rgb(d699b6)
$purpleAlpha = d699b6
$grey0 = rgb(7a8478)
$grey0Alpha = 7a8478
$grey1 = rgb(859289)
$grey1Alpha = 859289
$grey2 = rgb(9da9a0)
$grey2Alpha = 9da9a0
$statusline1 = rgb(a7c080)
$statusline1Alpha = a7c080
$statusline2 = rgb(d3c6aa)
$statusline2Alpha = d3c6aa
$statusline3 = rgb(e67e80)
$statusline3Alpha = e67e80
